name: test
on: 
  workflow_dispatch: 
    inputs:
      file-path: # id of input
        description: "Path to test script"
        required: true
        default: "test-file.js"
jobs: 
  test: 
    name: test job
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
        with: 
          debug: true
      - run: echo hello
      
