name: test
on: 
  workflow_dispatch: 
jobs: 
  test: 
    name: test job
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
        with: 
          debug: true
      - run: echo hello
      - run: |
              touch test.ttt
      - run: |
              ls
      - run: |
              pwd
